version: 2

sphinx:
    configuration: docs/conf.py

python:
   install:
   - method: pip
     path: .

conda:
  environment: "docs/environment-docs.yml"

build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-4.10"
